DT_SERIES_ERROR = "pd.Series index must be pd.DateTimeIndex"
